/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author hemin
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    
    public CreatePersonJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        userProcessContainer = container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblSectionPersonInfo = new javax.swing.JLabel();
        lblSectionHomeAdd = new javax.swing.JLabel();
        lblSectionWorkAdd = new javax.swing.JLabel();
        lblStateH = new javax.swing.JLabel();
        lblCityH = new javax.swing.JLabel();
        lblStAddressH = new javax.swing.JLabel();
        lblZipH = new javax.swing.JLabel();
        lblPhoneH = new javax.swing.JLabel();
        lblStateW = new javax.swing.JLabel();
        lblCityW = new javax.swing.JLabel();
        lblhStAddressW = new javax.swing.JLabel();
        lblZipW = new javax.swing.JLabel();
        lblPhoneW = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtStAddressH = new javax.swing.JTextField();
        txtStateH = new javax.swing.JTextField();
        txtZipH = new javax.swing.JTextField();
        txtCityH = new javax.swing.JTextField();
        txtPhoneH = new javax.swing.JTextField();
        txtStAddressW = new javax.swing.JTextField();
        txtCityW = new javax.swing.JTextField();
        txtStateW = new javax.swing.JTextField();
        txtZipW = new javax.swing.JTextField();
        txtPhoneW = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblAnnualInc = new javax.swing.JLabel();
        txtAnnualInc = new javax.swing.JTextField();

        setBackground(new java.awt.Color(85, 188, 231));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Create Person");

        lblFName.setText("First Name");

        lblLName.setText("Last Name");

        lblSSN.setText("Social Security Number");

        lblAge.setText("Age");

        lblSectionPersonInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSectionPersonInfo.setText("Personal Information");

        lblSectionHomeAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSectionHomeAdd.setText("Home Address");

        lblSectionWorkAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSectionWorkAdd.setText("Work Address");

        lblStateH.setText("State");

        lblCityH.setText("City");

        lblStAddressH.setText("Street Address");

        lblZipH.setText("Zip Code");

        lblPhoneH.setText("Phone");

        lblStateW.setText("State");

        lblCityW.setText("City");

        lblhStAddressW.setText("Street Address");

        lblZipW.setText("Zip Code");

        lblPhoneW.setText("Phone");

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        txtStAddressH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStAddressHActionPerformed(evt);
            }
        });

        txtStateH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateHActionPerformed(evt);
            }
        });

        txtZipH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipHActionPerformed(evt);
            }
        });

        txtCityH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityHActionPerformed(evt);
            }
        });

        txtPhoneH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneHActionPerformed(evt);
            }
        });

        txtStAddressW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStAddressWActionPerformed(evt);
            }
        });

        txtCityW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityWActionPerformed(evt);
            }
        });

        txtStateW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateWActionPerformed(evt);
            }
        });

        txtZipW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipWActionPerformed(evt);
            }
        });

        txtPhoneW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneWActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblAnnualInc.setText("Annual Income");

        txtAnnualInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnualIncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSectionWorkAdd)
                            .addComponent(lblZipH)
                            .addComponent(lblSectionHomeAdd)
                            .addComponent(lblAnnualInc)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStAddressH)
                                    .addComponent(lblPhoneH)
                                    .addComponent(lblZipW)
                                    .addComponent(lblPhoneW))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtStAddressH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtStAddressW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(19, 19, 19)
                                                    .addComponent(lblStateH)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(lblCityH)
                                                            .addGap(26, 26, 26)
                                                            .addComponent(txtCityH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(lblCityW)
                                                            .addGap(25, 25, 25)
                                                            .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblStateW)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, 0))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblhStAddressW)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(lblTitle))
                            .addComponent(lblSectionPersonInfo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFName)
                                    .addComponent(lblLName)
                                    .addComponent(lblSSN)
                                    .addComponent(lblAge))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnnualInc, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(169, 169, 169)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSubmit)
                .addGap(304, 304, 304))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSectionPersonInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLName)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnualInc)
                    .addComponent(txtAnnualInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSectionHomeAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStAddressH)
                    .addComponent(txtStAddressH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityH)
                    .addComponent(txtCityH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipH)
                    .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStateH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSectionWorkAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhStAddressW)
                            .addComponent(txtStAddressW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCityW)
                            .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStateW)
                            .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipW))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtStAddressHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStAddressHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStAddressHActionPerformed

    private void txtStateHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateHActionPerformed

    private void txtZipHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipHActionPerformed

    private void txtCityHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityHActionPerformed

    private void txtPhoneHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneHActionPerformed

    private void txtStAddressWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStAddressWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStAddressWActionPerformed

    private void txtCityWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityWActionPerformed

    private void txtStateWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateWActionPerformed

    private void txtZipWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipWActionPerformed

    private void txtPhoneWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneWActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

	String firstName = txtFName.getText();
	String lastName = txtLName.getText();
	String SSNStr = txtSSN.getText();
	String ageStr = txtAge.getText();
        String annualIncStr = txtAnnualInc.getText();
	String homeStreet = txtStAddressH.getText();
	String homeCity = txtCityH.getText();
	String homeState = txtStateH.getText();
	String homeZipCodeStr = txtZipH.getText();
	String homePhoneStr = txtPhoneH.getText();
	String workStreet = txtStAddressW.getText();
	String workCity = txtCityW.getText();
	String workState = txtStateW.getText();
	String workZipCodeStr = txtZipW.getText();
	String workPhoneStr = txtPhoneW.getText();

	// Validate mandatory fields
	if (firstName.isBlank() || lastName.isBlank() || SSNStr.isBlank() || ageStr.isBlank() || annualIncStr.isBlank() ||
		homeStreet.isBlank() || homeCity.isBlank() || homeState.isBlank() || homeZipCodeStr.isBlank() ||
		workStreet.isBlank() || workCity.isBlank() || workState.isBlank() || workZipCodeStr.isBlank()) {
		JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
		return;
	}

	// Validate age SSN and annual income
	try {
		byte age = Byte.parseByte(ageStr);
                int SSN = Integer.parseInt(SSNStr);
                Double annualInc = Double.parseDouble(annualIncStr);
                
             
	} catch (Exception e) {
		JOptionPane.showMessageDialog(null, "Please check your age, SSN and/or annual Income", "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}
        
        // Validate home and work phone no
        
        try {
		long workPhone = Long.parseLong(workPhoneStr);
                long homePhone = Long.parseLong(homePhoneStr);
            
	} catch (Exception e) {
		JOptionPane.showMessageDialog(null, "Please check your work/home phone no", "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}

        // Validate home and work Zip code
        try {
		int workPhone = Integer.parseInt(homeZipCodeStr);
                int homePhone = Integer.parseInt(homeZipCodeStr);
            
	} catch (Exception e) {
		JOptionPane.showMessageDialog(null, "Please check your work/home Zip code", "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}
        
        
	// Create new Person object
	Person p = personDirectory.addPerson();

	// Set person's details
	p.setFirstName(firstName);
	p.setLastName(lastName);
	p.setSSN(Integer.parseInt(SSNStr));
	p.setAge(Byte.parseByte(ageStr));
        p.setAnnualIncome(Double.parseDouble(annualIncStr));

	// Set home and work addresses using the setters
	p.setHomeAddress(homeStreet, homeCity, homeState, homeZipCodeStr, Long.parseLong(homePhoneStr));
	p.setWorkAddress(workStreet, workCity, workState, workZipCodeStr, Long.parseLong(workPhoneStr));

	// Show confirmation message
	JOptionPane.showMessageDialog(this, "Person successfully created.", "Information", JOptionPane.INFORMATION_MESSAGE);

	// Clear input fields after creation
	txtFName.setText("");
	txtLName.setText("");
	txtSSN.setText("");
	txtAge.setText("");
        txtAnnualInc.setText("");
	txtStAddressH.setText("");
	txtCityH.setText("");
	txtStateH.setText("");
	txtZipH.setText("");
	txtPhoneH.setText("");
	txtStAddressW.setText("");
	txtCityW.setText("");
	txtStateW.setText("");
	txtZipW.setText("");
	txtPhoneW.setText("");

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtAnnualIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnualIncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnualIncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAnnualInc;
    private javax.swing.JLabel lblCityH;
    private javax.swing.JLabel lblCityW;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblPhoneH;
    private javax.swing.JLabel lblPhoneW;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSectionHomeAdd;
    private javax.swing.JLabel lblSectionPersonInfo;
    private javax.swing.JLabel lblSectionWorkAdd;
    private javax.swing.JLabel lblStAddressH;
    private javax.swing.JLabel lblStateH;
    private javax.swing.JLabel lblStateW;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZipH;
    private javax.swing.JLabel lblZipW;
    private javax.swing.JLabel lblhStAddressW;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnualInc;
    private javax.swing.JTextField txtCityH;
    private javax.swing.JTextField txtCityW;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPhoneH;
    private javax.swing.JTextField txtPhoneW;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStAddressH;
    private javax.swing.JTextField txtStAddressW;
    private javax.swing.JTextField txtStateH;
    private javax.swing.JTextField txtStateW;
    private javax.swing.JTextField txtZipH;
    private javax.swing.JTextField txtZipW;
    // End of variables declaration//GEN-END:variables
}
