/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author hemin
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonJPanel
     */
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Person person;
    
    public ViewPersonJPanel(JPanel userProcessContainer, PersonDirectory directory, Person person) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.person = person;

        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSSN = new javax.swing.JLabel();
        lblhStAddressW = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblZipW = new javax.swing.JLabel();
        lblSectionPersonInfo = new javax.swing.JLabel();
        lblSectionHomeAdd = new javax.swing.JLabel();
        lblSectionWorkAdd = new javax.swing.JLabel();
        lblStateH = new javax.swing.JLabel();
        lblPhoneW = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblCityH = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblStAddressH = new javax.swing.JLabel();
        txtStAddressH = new javax.swing.JTextField();
        lblZipH = new javax.swing.JLabel();
        lblPhoneH = new javax.swing.JLabel();
        txtStateH = new javax.swing.JTextField();
        txtZipH = new javax.swing.JTextField();
        txtCityH = new javax.swing.JTextField();
        txtPhoneH = new javax.swing.JTextField();
        txtStAddressW = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        txtCityW = new javax.swing.JTextField();
        txtStateW = new javax.swing.JTextField();
        txtZipW = new javax.swing.JTextField();
        txtPhoneW = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblStateW = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        lblCityW = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblAnnualInc = new javax.swing.JLabel();
        txtAnnualInc = new javax.swing.JTextField();

        setBackground(new java.awt.Color(85, 188, 231));

        lblSSN.setText("Social Security Number");

        lblhStAddressW.setText("Street Address");

        lblAge.setText("Age");

        lblZipW.setText("Zip Code");

        lblSectionPersonInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSectionPersonInfo.setText("Personal Information");

        lblSectionHomeAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSectionHomeAdd.setText("Home Address");

        lblSectionWorkAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSectionWorkAdd.setText("Work Address");

        lblStateH.setText("State");

        lblPhoneW.setText("Phone");

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblCityH.setText("City");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblStAddressH.setText("Street Address");

        txtStAddressH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStAddressHActionPerformed(evt);
            }
        });

        lblZipH.setText("Zip Code");

        lblPhoneH.setText("Phone");

        txtStateH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateHActionPerformed(evt);
            }
        });

        txtZipH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipHActionPerformed(evt);
            }
        });

        txtCityH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityHActionPerformed(evt);
            }
        });

        txtPhoneH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneHActionPerformed(evt);
            }
        });

        txtStAddressW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStAddressWActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtCityW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityWActionPerformed(evt);
            }
        });

        txtStateW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateWActionPerformed(evt);
            }
        });

        txtZipW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipWActionPerformed(evt);
            }
        });

        txtPhoneW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneWActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("View Person");

        lblStateW.setText("State");

        lblFName.setText("First Name");

        lblCityW.setText("City");

        lblLName.setText("Last Name");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblAnnualInc.setText("Annual Income");

        txtAnnualInc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnualIncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSectionHomeAdd)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblStAddressH)
                                        .addComponent(lblPhoneH))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtStAddressH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblCityH))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblStateH)))
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtCityH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(lblSectionPersonInfo)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSectionWorkAdd)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblZipW)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblhStAddressW, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblPhoneW)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtStAddressW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblCityW))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblStateW)))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(btnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate)
                                        .addGap(220, 220, 220)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFName)
                                        .addComponent(lblLName)
                                        .addComponent(lblSSN)
                                        .addComponent(lblAge)
                                        .addComponent(lblAnnualInc))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAnnualInc, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblZipH))))
                .addGap(46, 46, 46))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPhoneH, txtStAddressH, txtZipH});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPhoneW, txtStAddressW, txtZipW});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCityW, txtStateW});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSectionPersonInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLName)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnualInc)
                    .addComponent(txtAnnualInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(lblSectionHomeAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStAddressH)
                    .addComponent(txtStAddressH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCityH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipH)
                    .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStateH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSectionWorkAdd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhStAddressW)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStAddressW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCityW)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZipW)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStateW)
                        .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtStAddressHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStAddressHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStAddressHActionPerformed

    private void txtStateHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateHActionPerformed

    private void txtZipHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipHActionPerformed

    private void txtCityHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityHActionPerformed

    private void txtPhoneHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneHActionPerformed

    private void txtStAddressWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStAddressWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStAddressWActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManagePersonJPanel managePersonJPanel = (ManagePersonJPanel) lastPanel;
        managePersonJPanel.populateData();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous (userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCityWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityWActionPerformed

    private void txtStateWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateWActionPerformed

    private void txtZipWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipWActionPerformed

    private void txtPhoneWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneWActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstName = txtFName.getText();
        String lastName = txtLName.getText();
        String SSNStr = txtSSN.getText();
        String ageStr = txtAge.getText();
        String annualIncStr = txtAnnualInc.getText();

        String homeStreet = txtStAddressH.getText();
        String homeCity = txtCityH.getText();
        String homeState = txtStateH.getText();
        String homeZipStr = txtZipH.getText();
        String homePhoneStr = txtPhoneH.getText();

        String workStreet = txtStAddressW.getText();
        String workCity = txtCityW.getText();
        String workState = txtStateW.getText();
        String workZipStr = txtZipW.getText();
        String workPhoneStr = txtPhoneW.getText();

        // Validate mandatory fields
        if (firstName.isBlank() || lastName.isBlank() || SSNStr.isBlank() || ageStr.isBlank() || annualIncStr.isBlank() ||
            homeStreet.isBlank() || homeCity.isBlank() || homeState.isBlank() || homeZipStr.isBlank() || homePhoneStr.isBlank() ||
            workStreet.isBlank() || workCity.isBlank() || workState.isBlank() || workZipStr.isBlank() || workPhoneStr.isBlank()) 
        {
            JOptionPane.showMessageDialog(null, "All fields are mandatory.");
            return;
        }
        
        	// Validate age SSN and annual income
	try {
		byte age = Byte.parseByte(ageStr);
                int SSN = Integer.parseInt(SSNStr);
                Double annualInc = Double.parseDouble(annualIncStr);
                
             
	} catch (Exception e) {
		JOptionPane.showMessageDialog(null, "Please check your age, SSN and/or annual Income", "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}
        
        // Validate home and work phone no
        
        try {
		long workPhone = Long.parseLong(workPhoneStr);
                long homePhone = Long.parseLong(homePhoneStr);
            
	} catch (Exception e) {
		JOptionPane.showMessageDialog(null, "Please check your work/home phone no", "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}

        // Validate home and work Zip code
        try {
		int workPhone = Integer.parseInt(homeZipStr);
                int homePhone = Integer.parseInt(homeZipStr);
            
	} catch (Exception e) {
		JOptionPane.showMessageDialog(null, "Please check your work/home Zip code", "Warning", JOptionPane.WARNING_MESSAGE);
		return;
	}

        // Update the Person object
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setSSN(Integer.parseInt(SSNStr));
        person.setAge(Byte.parseByte(ageStr));
        person.setAnnualIncome(Double.parseDouble(annualIncStr));
        person.setHomeAddress(homeStreet, homeCity, homeState, homeZipStr, Long.parseLong(homePhoneStr));
        person.setWorkAddress(workStreet, workCity, workState, workZipStr, Long.parseLong(workPhoneStr));

        JOptionPane.showMessageDialog(null, "Person information successfully updated.", "Information", JOptionPane.INFORMATION_MESSAGE);

        setViewMode(); // Switch to view mode after saving
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtAnnualIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnualIncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnualIncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAnnualInc;
    private javax.swing.JLabel lblCityH;
    private javax.swing.JLabel lblCityW;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblPhoneH;
    private javax.swing.JLabel lblPhoneW;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSectionHomeAdd;
    private javax.swing.JLabel lblSectionPersonInfo;
    private javax.swing.JLabel lblSectionWorkAdd;
    private javax.swing.JLabel lblStAddressH;
    private javax.swing.JLabel lblStateH;
    private javax.swing.JLabel lblStateW;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZipH;
    private javax.swing.JLabel lblZipW;
    private javax.swing.JLabel lblhStAddressW;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAnnualInc;
    private javax.swing.JTextField txtCityH;
    private javax.swing.JTextField txtCityW;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtPhoneH;
    private javax.swing.JTextField txtPhoneW;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStAddressH;
    private javax.swing.JTextField txtStAddressW;
    private javax.swing.JTextField txtStateH;
    private javax.swing.JTextField txtStateW;
    private javax.swing.JTextField txtZipH;
    private javax.swing.JTextField txtZipW;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
 
    txtFName.setText(person.getFirstName());
    txtLName.setText(person.getLastName());
    txtSSN.setText(String.valueOf(person.getSSN()));
    txtAge.setText(String.valueOf(person.getAge()));
    txtAnnualInc.setText(String.valueOf(person.getAnnualIncome()));
    
    Address homeAddress = person.getHomeAddress();
    txtStAddressH.setText(homeAddress.getStreet());
    txtCityH.setText(homeAddress.getCity());
    txtStateH.setText(homeAddress.getState());
    txtZipH.setText(homeAddress.getZipCode());
    txtPhoneH.setText(String.valueOf(homeAddress.getPhoneNumber()));
    
    Address workAddress = person.getWorkAddress();
    txtStAddressW.setText(workAddress.getStreet());
    txtCityW.setText(workAddress.getCity());
    txtStateW.setText(workAddress.getState());
    txtZipW.setText(workAddress.getZipCode());
    txtPhoneW.setText(String.valueOf(workAddress.getPhoneNumber()));
    
    }

    private void setViewMode() {
  
    txtFName.setEnabled(false);
    txtLName.setEnabled(false);
    txtSSN.setEnabled(false);
    txtAge.setEnabled(false);
    txtAnnualInc.setEnabled(false);

    txtStAddressH.setEnabled(false);
    txtCityH.setEnabled(false);
    txtStateH.setEnabled(false);
    txtZipH.setEnabled(false);
    txtPhoneH.setEnabled(false);
    
    txtStAddressW.setEnabled(false);
    txtCityW.setEnabled(false);
    txtStateW.setEnabled(false);
    txtZipW.setEnabled(false);
    txtPhoneW.setEnabled(false);

  
    btnSave.setEnabled(false);
    btnUpdate.setEnabled(true); 
    }

    private void setEditMode() {
    txtFName.setEnabled(true);
    txtLName.setEnabled(true);
    txtSSN.setEnabled(true);
    txtAge.setEnabled(true);
    txtAnnualInc.setEnabled(true);
    
    txtStAddressH.setEnabled(true);
    txtCityH.setEnabled(true);
    txtStateH.setEnabled(true);
    txtZipH.setEnabled(true);
    txtPhoneH.setEnabled(true);
    
    txtStAddressW.setEnabled(true);
    txtCityW.setEnabled(true);
    txtStateW.setEnabled(true);
    txtZipW.setEnabled(true);
    txtPhoneW.setEnabled(true);


    btnSave.setEnabled(true);
    btnUpdate.setEnabled(false); 
    }
}
